### ISSUE TITLE
Thank you for this!

### ISSUE THREAD

**Issue by bbecausereasonss** [divamgupta/diffusionbee-stable-diffusion-ui#1]
Finally a simple M1 GUI. Would be amazing to have IMG2IMG working /w ERSGAN and GFPGAN

**Comment by divamgupta** [comment]
You're welcome!

**Comment by andrewjrangel** [comment]
Yes, this is amazing! It works great as mentioned. I really hope this becomes precedent for future software. Just because we are all tech geeks does not mean we love jumping through hoops to install and run it.

**Comment by miolini** [comment]
Yes, thank you! You are amazing!

**Comment by harryshawk** [comment]
Yes -- very helpful.. it's nice being able to use my own machine!

**Comment by eggsyntax** [comment]
It's enormously appreciated!

**Comment by Itangalo** [comment]
+1 for this. Thanks a bunch!
I'm gonna start an issue to see if I can help with some basic documentation – I'd love to give something back.
