### ISSUE TITLE
Update: New version available...

### ISSUE THREAD

**Issue by Zimbakin** [divamgupta/diffusionbee-stable-diffusion-ui#109]
0.2.2 update from git hub alerts that there is a newer version available.
This refers back to your web site which, then downloads 0.2.1 (older version)

0.2.2

> A new version of DiffusionBee is available. Do you want to visit https://diffusionbee.com to update?

**Comment by darwiniandude** [comment]
Thanks, I also got the new prompt and ended up with 0.2.1 instead.

**Comment by Zimbakin** [comment]
Problem seems fixed in 0.3.0
