### ISSUE TITLE
MacOS 12.5.1 Requirement

### ISSUE THREAD

**Issue by justinormont** [divamgupta/diffusionbee-stable-diffusion-ui#11]
Is there any reason for the macOS 12.5.1 requirement?

https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/blob/384001c8dc6a7f79e00a1f20ea2e098e6965744c/electron_app/vue.config.js#L26-L28

I have no issue running Stable Diffusion under macOS 12.4 on a M1 Max.

**Comment by jococo** [comment]
I ran into the same issue. Did a Software Update and am now on version 12.3 so can't run this software.

**Comment by davidgourde** [comment]
Same issue. I'm on 12.5 (latest) and cannot run it, it's still asking for 12.5.1

**Comment by PeterHaughie** [comment]
Same here.

**Comment by divamgupta** [comment]
Fixed
