### ISSUE TITLE
[BUG] Hitting enter when focused on the new Seed field crashes app

### ISSUE THREAD

**Issue by TomSadira777** [divamgupta/diffusionbee-stable-diffusion-ui#115]
Repro:
1. open the app
2. enter any prompt
3. open advanced options
4. click into Seed field and enter any number
5. hit enter 
6. ---> app crashes and restarts

I can repro in a vid if that would help

I'm using Version 0.2.2 (0004)

Thx for all your hard work on this app. I love it!

**Comment by divamgupta** [comment]
Thanks for reporting it! Will be fixed in next release.

**Comment by TomSadira777** [comment]
np dude! thx for the quick fix.
