### ISSUE TITLE
Feature Request [Enable highlighting prompts in history]

### ISSUE THREAD

**Issue by prestmango** [divamgupta/diffusionbee-stable-diffusion-ui#131]
Having prompt history be highlight-able for quick copy and paste of old prompts

**Comment by camilovietnam** [comment]
Agree, I can see the prompts in the History tab but they can't be selected with your mouse, so if you want to reuse them you have to type them all over again.

**Comment by divamgupta** [comment]
https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/146ed77ac74e7948a9163eeb508fa1f4bbcde03d
