### ISSUE TITLE
Feat: brew cask installation

### ISSUE THREAD

**Issue by Just-Moh-it** [divamgupta/diffusionbee-stable-diffusion-ui#14]
I'd love to see a brew cask installation formula for this :) (I default to installing apps on my Mac that way, like many other people)

**Comment by signalwerk** [comment]
@Just-Moh-it great idea! If you would like to contribute a formula, so it becomes available, a pull-request to the [repository](https://github.com/Homebrew/homebrew-core) would be highly appreciated and you could become the maintainer. There you can also find support. Sometimes it needs someone to give the first effort and then the community can help out.

**Comment by Just-Moh-it** [comment]
@signalwerk, I would have loved to, but I don't really have any experience with brew apart from installing things. I'd be happy to research about it and submit a pull request though :)

(if it doesn't require an account from the creator or any other non-controllable things) 😄

**Comment by CarlosMendonca** [comment]
I have a formula ready to submit to homebrew-cask, which is pretty straightforward given how you setup distribution through GH, but since this repository is too new, it fails basic testing. I can create and send the PR to their repo after your repo is >= 30 days old.

**Comment by nickv2002** [comment]
FWIW: This repo is now more than 30 days old.
Thanks to anyone who cask-ifies it!

**Comment by CarlosMendonca** [comment]
I was about to submit it, but it seems like someone was faster: https://github.com/Homebrew/homebrew-cask/pull/132843
