### ISSUE TITLE
Where are temp files located in 0.3 on MacOS?

### ISSUE THREAD

**Issue by yisforyeti** [divamgupta/diffusionbee-stable-diffusion-ui#145]
It was much easier to "bulk save" by copying the temp files out into a more permanent location. Where are they currently located in MacOS? If it is in the "blob_storage" in <user>/Library/Appliation Support/Diffusion Bee, can the change be reverted to save actual pngs?

**Comment by jemueller** [comment]
they're in ```~/.diffusionbee/images``` now

**Comment by yisforyeti** [comment]
Thank you!!!
