### ISSUE TITLE
Feature Request: Possible to open History Tab while generating

### ISSUE THREAD

**Issue by DCNielsen** [divamgupta/diffusionbee-stable-diffusion-ui#155]
I'd like to be able to look over some previous prompts and think through my next Generation but the UI is locked until the Generation completes.

**Comment by camilovietnam** [comment]
@DCNielsen Weird, I am able to browse the History tab even while the image is being generated. This has been the case since release 0.2.0

https://user-images.githubusercontent.com/49581907/193440907-29b0d792-5b0a-493e-b3b6-69dad6cec74d.mov
