### ISSUE TITLE
Feature Request: Add Notification Sound or Text when images are complete

### ISSUE THREAD

**Issue by TheCatFace** [divamgupta/diffusionbee-stable-diffusion-ui#165]
Having a subtle "Ding" sound and an "Images Complete" pop-up notification (for hearing impaired) occur when users are alt-tabbed would be a great way to cut down on the need to compulsively check the progress of impending images.

**Comment by ahhyeah** [comment]
Yes please! And an estimated time remaining would be amazing too!
