### ISSUE TITLE
Feature request: image2image, move image over to source.

### ISSUE THREAD

**Issue by greggh** [divamgupta/diffusionbee-stable-diffusion-ui#166]
I'd like to be able to generate an image with img2img and next to the "save image" button I would like there to be a button that lets me take the new image from the right and move it over to the left, so its the new source image. So I can quickly run through many generations.

**Comment by iangilman** [comment]
I would like this for every image in the history, regardless of whether it came from img2img!

**Comment by greggh** [comment]
Implemented in 1.2.0
