### ISSUE TITLE
Feature Request: Allow copying of text promts from History

### ISSUE THREAD

**Issue by TheCatFace** [divamgupta/diffusionbee-stable-diffusion-ui#172]
While it is easy to alter the immediately previous Text To Image prompt to explore prompt variations, allowing copying/pasting of text prompts from History would make it easier to try variations on prompts from further back in History. Currently the text prompts in History are not able to be selected/copied/pasted.

<img width="549" alt="Screen Shot 2022-10-02 at 1 53 38 PM" src="https://user-images.githubusercontent.com/31554256/193475799-b6fde168-4bd9-431c-9d79-b9fbfef5d51a.png">

**Comment by Leland** [comment]
Duplicate of #123

**Comment by TheCatFace** [comment]
my bad!
