### ISSUE TITLE
Feature Request (longtime) : convert to Core ML

### ISSUE THREAD

**Issue by zehrer** [divamgupta/diffusionbee-stable-diffusion-ui#197]
If I get it right (but please correct me if I am wrong) currently the app runs python in the background which is very bad from performance perspective.

I would suggest to convert  some (e.g. PyTorch) or even all models to CoreML and use the more native implementation on a M1/M2 Mac. I hope this would use better the Neural engine. 
Any comments from the experts?

**Comment by lasconic** [comment]
Interesting read: https://wandb.ai/capecape/stable_diffusions/reports/Speed-Up-Stable-Diffusion-on-Your-M1Pro-Macbook-Pro--VmlldzoyNjY0ODYz

**Comment by divamgupta** [comment]
Yeah, it seems TF is faster.

**Comment by zehrer** [comment]
You don't like to use this as this app for Mac?

**Comment by drawingthesun** [comment]
@zehrer The link showed that Tensorflow is working much faster than pytorch at the current time for m1 mac.

 I could be wrong but my interpretation is that if DiffusionBee switched to pytorch now, we would see a performance decrease, not increase.

Until alternatives show increased performance, I think the best you can get at the moment for m1 is what DiffusionBee currently offers.

**Comment by andrewtlove** [comment]
https://github.com/apple/ml-stable-diffusion
