### ISSUE TITLE
reuse existing model if already downloaded?

### ISSUE THREAD

**Issue by ericries** [divamgupta/diffusionbee-stable-diffusion-ui#2]
Or could you add a preference/log to either let the user know where the model will download to or let the user point to one if already present?

**Comment by abulka** [comment]
The `Logs` tab of the UI has a clue:

    /Users/YOURUSERNAME/.diffusionbee/downloads

**Comment by abulka** [comment]
I managed to move the large downloads directory to another disk.

0. Make a directory on your external drive `/Volumes/SSD/Data/diffusionbee/`
1. `mv ~/.diffusionbee/downloads /Volumes/SSD/Data/diffusionbee/downloads`
2. `ln -s /Volumes/SSD/Data/diffusionbee/downloads ~/.diffusionbee/downloads`
