### ISSUE TITLE
Images larger than 640x768 are blank or corrupted

### ISSUE THREAD

**Issue by callmetim01** [divamgupta/diffusionbee-stable-diffusion-ui#20]
Hello,
Thank you for making this project. I'm encountering an issue where making the image size larger than 640x768 results in black or "corrupted images". I can generate images up to 768x640 or 640x768, but as soon as both dimensions are 768, I get the unintended results. This happens regardless of the Steps or Guidance Scale values, and results in a similar image output regardless if prompt.

This is on a 16" MacBook Pro, w/ M1 Max and 64 GB of RAM. I have attached 2 versions of the "corrupted" images that have been generated. Reducing the image output results in a correctly generated image, when retaining all other parameters.
![Untitled12](https://user-images.githubusercontent.com/113373782/189709362-d529e6a8-367d-4e6f-93e3-a3c051816f3c.png)
![Untitled13](https://user-images.githubusercontent.com/113373782/189709369-7b44c29f-b290-4ede-924a-66d92cbbd5fa.png)

Thanks again for all your work on this project. It's great!

**Comment by ee0pdt** [comment]
The model is trained on 512 x 512 images. It doesn’t do well on resolutions higher than that. They recommend leaving at least one dimension at 512. 

I tend to upscale with tools like GFPGAN afterwards

**Comment by callmetim01** [comment]
Ah, understood. It's actually been giving me consistent results as long as one dimension is below 768, but thank you for clarifying the limitations of the model.

**Comment by greggh** [comment]
For this, I use Upscayl. A great front end for multiple tools like RealESRGAN and RealSR.

https://github.com/upscayl/upscayl
