### ISSUE TITLE
[question] Diffusion Bee virtual environment

### ISSUE THREAD

**Issue by shepherd1530** [divamgupta/diffusionbee-stable-diffusion-ui#207]
Does diffusion bee ship a virtual environment with the installation? If yes, what's the path to it? I am trying to run the app using the source code but the script can't find Tensorflow which indicates that I might be missing a virtual env.

**Comment by shepherd1530** [comment]
I missed the PyInstaller entry in the setup scripts. Another alternative was to just install the m1 requirements on my local virtual env.

**Comment by ZahidServers** [comment]
@shepherd1530 Hey how to connect with backend? I am also trying to build it from source
