### ISSUE TITLE
Max Batch increase?

### ISSUE THREAD

**Issue by enzyme69** [divamgupta/diffusionbee-stable-diffusion-ui#222]
Is it possible to make 100-150 generation? I need to run it overnight. 

Also would be nice to be able to assign variations in batch (dog, cat, fox) looping for example.

**Comment by TheCatFace** [comment]
+1

**Comment by Gitterman69** [comment]
all settings should have a wider range of choosable options.... its a bit bland compared to automatic1111

**Comment by enzyme69** [comment]
Thanks for max batch now can be set to 50 and 100! 

In Mac:
Shift + CMD + G
 /Users/yourname/.diffusionbee/images
 
 Batch copy and save outputs.
