### ISSUE TITLE
Location of downloaded models/files?

### ISSUE THREAD

**Issue by byGits** [divamgupta/diffusionbee-stable-diffusion-ui#224]
Hello,

After running DiffusionBee for the first time, it downloads about 4-6GB of Models/Data.

But when I tried uninstalling it (using AppCleaner) only the 2GB diffusionbee.app and a few folders with less than 1MB were found inside Application Support.

May I ask where are those downloaded models are stored so I can delete them manually?

**Comment by pravindahal** [comment]
It seems to be in `/Users/$USER/.diffusionbee/downloads` where `$USER` is your username.

**Comment by byGits** [comment]
> It seems to be in `/Users/$USER/.diffusionbee/downloads` where `$USER` is your username.

That's it, thanks!

`~/.diffusionbee`
