### ISSUE TITLE
How to run from source code?

### ISSUE THREAD

**Issue by sa1i** [divamgupta/diffusionbee-stable-diffusion-ui#226]
Hey I wanna test negative prompt feature, I see your hard work on this, I wanna put some efforts on this project, how can I test and run local from source code?

Can you give me some simple guides for development?

thanks!

**Comment by BenRacicot** [comment]
There's a thread here https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/62

**Comment by sa1i** [comment]
@BenRacicot thanks! 
I will follow this thread
