### ISSUE TITLE
No GPU acceleraction on MacBook Pro with AMD Graphics card?

### ISSUE THREAD

**Issue by zwzheng45** [divamgupta/diffusionbee-stable-diffusion-ui#227]
I'm using a 2019 16 inch MacBook Pro with a 0.3.0 release of Diffusion Bee (which is the latest release I can find for x86 Macs), but it doesn't seems to use the GPU while it's generating, and it's really slow while doing that.

BTW do you still support x86 version for this software? I didn't see any x86 release after 0.3.0.

**Comment by lasc** [comment]
same for imac with AMD Radeon  5700

**Comment by zwzheng45** [comment]
The newest 1.5.1 x86 release is supported for Radeon GPU acceleraction. For those Macs that have two graphic cards you need to switch to AMD graphic cards manually in the system battery settings otherwise it will use the slow Intel GPU when processing it.

**Comment by lasc** [comment]
I am on 1.5.1 on 2020 iMac and its not using GPU. No switch for graphic cards in setting also

**Comment by sblument** [comment]
Use of GPU appears to be automatic. Not sure how it determines
compatibility for GPU vs CPU mode
