### ISSUE TITLE
Show history of prompts and generated images

### ISSUE THREAD

**Issue by dwt** [divamgupta/diffusionbee-stable-diffusion-ui#24]
This would allow to more easily experiment with variations of prompts and go back and change them later. Also Images aren't lost immediately after entering the next prompt.

This could also be a nice gateway into allowing prompts to be queued up to use the available compute optimally.

**Comment by dseddah** [comment]
Hi,
if you look at the logs window, you'll see that the images are saved in the /tmp/samples directory. Which will of course be deleted upon reboot :(

What would be great would be to save the prompt and options as the filenames  (eg. "Charles Dickens in Simpson style. High details.png"

**Comment by Leland** [comment]
This landed in eed8628b51248e298eea38c0bb3988a0dfa63beb, and can be closed.

<img width="437" alt="image" src="https://user-images.githubusercontent.com/714017/193468887-5d444705-4519-4194-93a3-dc73afdc920f.png">
