### ISSUE TITLE
Feature Request: Improve Inpainting

### ISSUE THREAD

**Issue by EthanM25** [divamgupta/diffusionbee-stable-diffusion-ui#241]
Add the ability to change the size of the brush and the ability to zoom in/out of the image to make more precise adjustments.

**Comment by hkeely** [comment]
Yes, please. Seconded.

**Comment by Polyculturerawks** [comment]
Yes Please! Thirded!

**Comment by EthanM25** [comment]
1.4.2 brings the changes I was looking for, thanks!
