### ISSUE TITLE
Backend quit unexpectedly

### ISSUE THREAD

**Issue by peterneutron** [divamgupta/diffusionbee-stable-diffusion-ui#252]
OS: macOS Ventura 13.0 (22A380)
HW: Apple M1 (ARM64)
DiffusionBee: 1.4.0-arm64

![diffbee14](https://user-images.githubusercontent.com/60703175/198134566-aca165c7-540d-415e-b047-f18c707de601.png)

**Comment by osxdoc** [comment]
Same here

**Comment by divamgupta** [comment]
Yes, v1.4.0 does not work with Ventura.  I fix will be uploaded  soon.

**Comment by peterneutron** [comment]
Closing this because obviously I'am unable to properly read the release notes 🤦‍♀️ Sorry.
