### ISSUE TITLE
Backend quit unexpectedly: failed assertion `should be static because stitched op is static'

### ISSUE THREAD

**Issue by fortinmike** [divamgupta/diffusionbee-stable-diffusion-ui#255]
In the new 1.4.0 build on Intel and macOS Ventura:

Here is the full error:

```
Backend quit unexpectedly. /AppleInternal/Library/BuildRoots/810eba08-405a-11ed-86e9-6af958a02716/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Runtimes/MPSRuntime/Operations/GPUStitchedOps.mm:76: failed assertion `should be static because stitched op is static'
```

![Screenshot 2022-10-26 at 17 57 21](https://user-images.githubusercontent.com/118257/198146276-d837428d-6ec2-44c8-8809-f3be550396f1.png)

Thanks for bringing back the Intel build by the way!

**Comment by panckreous** [comment]
Samesies

**Comment by whosawhatsis** [comment]
Getting the same on an M1 Max running Ventura.

**Comment by EthanM25** [comment]
> In the new 1.4.0 build on Intel:
> 
> Here is the full error:
> 
> ```
> Backend quit unexpectedly. /AppleInternal/Library/BuildRoots/810eba08-405a-11ed-86e9-6af958a02716/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Runtimes/MPSRuntime/Operations/GPUStitchedOps.mm:76: failed assertion `should be static because stitched op is static'
> ```
> 
> ![Screenshot 2022-10-26 at 17 57 21](https://user-images.githubusercontent.com/118257/198146276-d837428d-6ec2-44c8-8809-f3be550396f1.png)
> 
> Thanks for bringing back the Intel build by the way!

This is an issue for everyone on Ventura. The dev is currently working on a fix.

**Comment by barryanders** [comment]
*downloads 1.4.0 and uses it whole downloading Ventura*
*updates to Ventura*
*tries to use 1.4.0 and then realizes it doesn't work on Ventura*

Should've read the release notes.

**Comment by EthanM25** [comment]
> 1. _downloads 1.4.0 and uses it whole downloading Ventura_
> 2. _updates to Ventura_
> 3. _tries to use 1.4.0 and then realizes it doesn't work on Ventura_
> 
> Should've read the release notes.

Haha, thats unfortunate. Hopefully a patch will be out relatively soon.

**Comment by fortinmike** [comment]
Whoops! I'm guilty of not reading the whole release notes... which is out of character to be honest ;)

Glad to hear @divamgupta is working on a fix.

**Comment by barryanders** [comment]
@fortinmike To be clear, I wasn't mocking you. I did exactly what I described. I read the feature list but didn't read the next line lol Surely it's not a huge thing. I'll look into it also, granted I probably won't be able to contribute but I'll try anyway.

**Comment by fortinmike** [comment]
@barryanders No worries, I did not read your comment that way at all. I'm just realizing that I should read more carefully next time :)

**Comment by divamgupta** [comment]
Fixed in the latest release. Could you pls confirm if that works for you.

**Comment by panckreous** [comment]
Hm, where does this leave me? I just assumed it was Ventura because of how great it's been at making so many things worse and outright just breaking others... then I immediately threw away everything I knew to follow @fortinmike

And you know what? If I could do it all again, I wouldn't change a thing. I cherished our time together.

**Comment by whosawhatsis** [comment]
1.4.2 seems to be working on ventura. Thanks!

**Comment by barryanders** [comment]
<img width="469" alt="Screenshot 2022-10-26 at 7 13 38 PM" src="https://user-images.githubusercontent.com/91902180/198161832-7489e8c6-f0c0-4caf-b4ff-cb54f0637eeb.png">

**Comment by fortinmike** [comment]
I can confirm that 1.4.2 starts on Ventura. However, do any of you that are running Ventura get fully black images?

Whatever mode I try, whatever prompt I try, I always get a black picture back.

![Screenshot 2022-10-26 at 20 49 14](https://user-images.githubusercontent.com/118257/198167421-b71f2217-5f02-4136-999a-15fe700cdc51.png)

I've seen mentions of a NSFW filter that should be disabled in [other](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/67) [issues](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/26) about blank images but did not find a setting for that anywhere; does one exist? And obviously this specific prompt should not trigger said filter even if it were ON.

**Comment by divamgupta** [comment]
@fortinmike is that on Intel mac with AMD GPU? They are not supported yet.

**Comment by EthanM25** [comment]
It's working fine for me, although I am on apple silicon. Probably some intel only bug.

**Comment by fortinmike** [comment]
@divamgupta Yes it is. MBP with Radeon Pro 5600M (which worked fine with 0.3.0). Now that's a bummer! At what level are those GPUs not supported anymore? What changed compared to 0.3.0 regarding AMD GPU support?

**Comment by divamgupta** [comment]
I have added the build for 1.4.3 . Can people confirm if that it working with AMD GPUs

**Comment by barryanders** [comment]
I've been using 1.4.3 for the last couple hours. No problems.

**Comment by bobmane** [comment]
I am running Ventura on an Intel Mac via OpenCore. I know this machine is not likely to do any AI app well but Diffusion Bee installed and I wanted to try it out. 16GB RAM. The graphics is Intel HD Graphics 40001536MB. 

Is this error still in effect for many people on Intel or is it just my machine? 

crashes upon hitting “Generate”

Backend quit unexpectedly. -[MTLHeapDescriptorInternal validateWithDevice:]:344: failed assertion `Heap Descriptor Validation
Placement heap type is not supported.
