### ISSUE TITLE
Version 1.4.3 update Quality for M1 ... hmmm

### ISSUE THREAD

**Issue by enzyme69** [divamgupta/diffusionbee-stable-diffusion-ui#273]
So just like what the title said, with M1 8GB, the generation takes 1 minutes ish now, which is good. However, the quality is indeed seems reduced so much than before. 

Is this something that could be improved just by increasing the steps value? 

You did note it on how the quality reduced, but faster. But how to counter this and find the balance?

Also by the way, the LOG still seems not in the right place, would be nice to see the log while processing and also now the log text has missing time value of how long it takes to generate the image. It used to show up.

**Comment by Leland** [comment]
Have you tried the [other version?](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.4.3) `DiffusionBee-1.4.3-arm64_TF_SD1.4_FP32`

Not seen anything glaringly worse here! Here's Al Pacino as Don Draper:

![ld33d3](https://user-images.githubusercontent.com/714017/199104477-203562bd-a1e0-4091-9312-a006c4d3214a.png)

**Comment by enzyme69** [comment]
Oh I see, there are 2 version for M1 machine. float 16 and float 32. Float 16 with SD1.5 = faster, and float 32 with SD1.4 = slower but higher quality. 

I will check, thanks!

But, isn't it Stable Diffusion 1.5 model supposed to produce higher quality result?

**Comment by enzyme69** [comment]
With fast version, the quality is not actually bad if the subject is close up:

![6de3d02af7e44e6d96e7c0f02871cf36](https://user-images.githubusercontent.com/3952687/199152829-323574b8-71f1-4815-a711-befc01527625.png)
![358543_apaintingofireneredvelvetinthestyleofwilliamhenrym](https://user-images.githubusercontent.com/3952687/199152894-9a5420b1-b5c3-43d1-b92d-a89a0065f2fa.png)


When faraway from camera, the details on face lost:
![456868_apaintingofireneredvelvetinthestyleofwilliamhenrym](https://user-images.githubusercontent.com/3952687/199153018-7cae8dd0-6bd5-4201-9762-193eb71b65e6.png)
![286062_apaintingofireneredvelvetinthestyleofwilliamhenrym](https://user-images.githubusercontent.com/3952687/199153105-150bbee9-6d52-4180-8441-b78286f67974.png)

**Comment by enzyme69** [comment]
I tried the other version. Quality VS Speed, I decided to pick speedy version. I just upres the good seed. Cheeers!
