### ISSUE TITLE
Feature Request: Switch Models

### ISSUE THREAD

**Issue by barryanders** [divamgupta/diffusionbee-stable-diffusion-ui#284]
Just a simple model selector. There's some cool ones [over here](https://huggingface.co/spaces/anzorq/finetuned_diffusion) that I'd like to switch to and use in DiffusionBee. In general, if users have their own models, it'd be nice if they could select them in DiffusionBee. Maybe DiffusionBee could even offer to convert them like mentioned in #197 so that they run faster. Or there could at least be a reference in the docs to how to convert models to run faster on a Mac.

**Comment by eAi** [comment]
I’d also like this for fine-tuned models from strmr.com

**Comment by barryanders** [comment]
Sorry, just realized this is essentially a duplicate of #10.
