### ISSUE TITLE
Question: 1.5 Inpainting model integrated?

### ISSUE THREAD

**Issue by Gitterman69** [divamgupta/diffusionbee-stable-diffusion-ui#292]
Is the 1.5 sd-inpainting model already integrated in diffusion bee?

[](https://huggingface.co/runwayml/stable-diffusion-inpainting)

**Comment by Gitterman69** [comment]
https://huggingface.co/runwayml/stable-diffusion-inpainting

**Comment by divamgupta** [comment]
Yes it is
