### ISSUE TITLE
Option to generate more than one sample

### ISSUE THREAD

**Issue by llimllib** [divamgupta/diffusionbee-stable-diffusion-ui#3]
When working with SD I generally like to generate at least a few samples per prompt, it would be great to add the option to set `n_samples`

**Comment by wpapper** [comment]
Adding onto this, one feature that would be very useful would be continuous generation. I personally leave DiffusionBee on in the background, and having it generate images in the background continuously (maybe up to a max) would give me many options to work with.

**Comment by harryshawk** [comment]
Both would be helpful

**Comment by airwindows** [comment]
Agree with the continuous generation: I would use this frequently.

I am creating folders named according to the prompt I'm using, and manually numbering my outputs (so far the highest is 50 samples, all run manually and numbered in the file export dialog by scrolling to the most recent picture and then typing in the next number)

This is definitely the sort of thing the program could be doing for me ;)

**Comment by dholbrook86** [comment]
> Adding onto this, one feature that would be very useful would be continuous generation. I personally leave DiffusionBee on in the background, and having it generate images in the background continuously (maybe up to a max) would give me many options to work with.

I would suggest creating a new separate thread for that and not tacking it onto this one. Generating more than one sample and continuous generation should be separate features.

Next question. I'm a 13 year software developer, (JavaScript, PHP mostly). How can I help with this project? Where would I even start?

**Comment by llimllib** [comment]
I'm gonna close this issue bc `0.2.0` add this, thanks @divamgupta !

**Comment by iangilman** [comment]
@dholbrook86 this probably isn't the answer you're looking for, but I'm getting the impression that while @divamgupta is doing an awesome job of charging forward with the code, interfacing with the community here is not his forte. If that's something you'd be up for helping out with, you might see about offering to help facilitate issues, pull requests, etc. Of course while you're at it, you can be getting to know the code base and contributing your own code as well.

Just a thought. If that's not your cup of tea, perhaps someone else can step into that role…
