### ISSUE TITLE
Question: are there instruction for a musician on how to install Dreambooth?

### ISSUE THREAD

**Issue by vpteittinen** [divamgupta/diffusionbee-stable-diffusion-ui#311]
I'm as far from a coder as one can be but I love creating images with Diffusion Bee (THANK YOU DIVAM!!!!) and would love to inject my stupid face into the AI images. Alas I don't know how to install Dreambooth... =(

**Comment by EthanM25** [comment]
Try this Google Colab: https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb?authuser=1#scrollTo=K6xoHWSsbcS3

**Comment by vpteittinen** [comment]
Oh, sorry, I meant to download and install into Diffusion Bee.

**Comment by vpteittinen** [comment]
Okay so if I got this right, I have to train the model in Colab and then install it into Diffusion Bee... I'll investigate further. Thanks!

**Comment by EthanM25** [comment]
> Okay so if I got this right, I have to train the model in Colab and then install it into Diffusion Bee... I'll investigate further. Thanks!

Yes that's correct.

**Comment by enzyme69** [comment]
Dreambooth inside Google Colab still feels complicated for me with some knowledge, basic python coding and scripting. I did use strmr and paid $3 (now $15), it does give me the ckpt with a single trained "sks man" token. 

Ideally we could just easily train our face model for multiple persons and use it inside DiffusionBee.

**Comment by vpteittinen** [comment]
> Dreambooth inside Google Colab still feels complicated for me with some knowledge, basic python coding and scripting. I did use strmr and paid $3 (now $15), it does give me the ckpt with a single trained "sks man" token.
> 
> Ideally we could just easily train our face model for multiple persons and use it inside DiffusionBee.

I was just looking at Astria last night! How dows it work - when you have the ckpt you just place it inside the downloads folder within the Diffusion Bee app? 
I read that some people have been having issues with Astria's site - not getting the download, having just a blank screen etc. Must be really popular at the moment...
