### ISSUE TITLE
Which version of the model is this 1.4 or 1.5?

### ISSUE THREAD

**Issue by preslavrachev** [divamgupta/diffusionbee-stable-diffusion-ui#32]

**Comment by nailuoGG** [comment]
Since the model file is located in  ~/.diffusionbee/downloads/sd-v1-4.ckpt

Obviously its version is 1.4

**Comment by mmmeff** [comment]
@nailuoGG 

_Obviously_ this person is asking before installing and running the application.

_Obviously_, responding to what is a perfectly normal question is unnecessarily toxic and unwelcoming behavior.

**Comment by rSh4d0w** [comment]
1.5 is not released yet, so yes this is indeed 1.4

**Comment by nailuoGG** [comment]
I apologize for my unfriendly behavior, I didn't mean to.

When I saw the issue, I thought the downloaded ckpt file would be a clear evidence. 

So I commented it, not realizing the unkind word

**Comment by nailuoGG** [comment]
@mmmeff 

I apologize for my unfriendly behavior, I didn't mean to.

When I saw the issue, I thought the downloaded ckpt file would be a clear evidence. 

So I commented it, not realizing the unkind word

**Comment by preslavrachev** [comment]
It's my turn to apologize too. I should have formulated my question in more detail. I did not look into the source code, indeed,  hoping that I'd be able to find the information in the README.

**Comment by lgrkvst** [comment]
Someone should save this thread as a reference to what humans on the internet _could_ be like. Never ever have I seen a quarrel get resolved so cleanly, quickly, with apologies and all. 

Bless you guys!
