### ISSUE TITLE
Custom Model CKPT and TDICT double size?

### ISSUE THREAD

**Issue by enzyme69** [divamgupta/diffusionbee-stable-diffusion-ui#325]
I am collecting some library of Custom Models, but my HDD is limited. At 2-7 GB, I also notice when imported CKPT model, DiffusionBee will also generate TDICT files.

I have a folder with CKPT and deleted some that already become TDICT --> I wonder if this is okey? Because I started noticing creashing happens in Back End. Was this caused by the DiffusionBee TDICT still needing CKPT? Or is it safe to delete CKPT?

<img width="637" alt="Screenshot 2022-11-17 at 11 57 36 am" src="https://user-images.githubusercontent.com/3952687/202328043-65193a66-f412-46be-84cf-16d77a424306.png">

**Comment by enzyme69** [comment]
From observation, the tdict of DiffusionBee might be enough to run the app and switching custom model. However better to backup the original CKPT just in case.

**Comment by CrudeDiatribe** [comment]
Indeed, it doesn't need the .ckpt file, but a couple of things: 

1. The released version will import some models without error but won't import them correctly (I know that _PaperCut_ and _Retro SF_ have this problem). 
2. The list of imported models and the path to their .tdict are stored in data.json in ~/.diffusionbee, if you launch an older version of Diffusion Bee it can (will?) overwrite data.json without your custom models as it doesn't know about custom models.
