### ISSUE TITLE
No ability to turn off "Pop!" sound after every completed diffusion

### ISSUE THREAD

**Issue by sj4nes** [divamgupta/diffusionbee-stable-diffusion-ui#329]
Is there a configuration setting for this? This is very distracting and a problem for those of us who batch prompts in the background while they do other work--which might require audio as well.

**Comment by EthanM25** [comment]
Hit the menu in the top right corner and click settings. You can disable the notification noise from there.

**Comment by sj4nes** [comment]
Pesky menu, hiding up there. :) Thanks.
