### ISSUE TITLE
Stable Diffusion 2.0 ckpt not loading

### ISSUE THREAD

**Issue by PeatedAF** [divamgupta/diffusionbee-stable-diffusion-ui#341]
Error Traceback (most recent call last):
File "convert_model.py", line 42, in <module>
AssertionError: ('shape mismatch at', 'model.diffusion_model.input_blocks.1.1.proj_in.weight', [320, 320], (320, 320, 1, 1))
[3356] Failed to execute script 'convert_model' due to unhandled exception!

**Comment by ghzgod** [comment]
What was the fix for this?

**Comment by eshack94** [comment]
@PeatedAF I'm also wondering. I'm seeing the same error while trying to import 768-v-ema.ckpt (Stable Diffusion 2.0).

I am going to re-open a new issue with this, since I'd like to understand the problem.
