### ISSUE TITLE
A Mode for 8GB M1 Machines

### ISSUE THREAD

**Issue by Schneppi** [divamgupta/diffusionbee-stable-diffusion-ui#37]
Would the app also run on 8GB M1 machines? Even if that meant it would run a lot slower?

Or will there ever be a version for 8GB M1 machines please?

**Comment by yuanyiming** [comment]
It works, but it's a little slow

**Comment by Schneppi** [comment]
> It works, but it's a little slow

Awesome! Thank you.

**Comment by divamgupta** [comment]
Actually a new version is coming soon. That will be faster on 8GB machines.
