### ISSUE TITLE
Safetensors support

### ISSUE THREAD

**Issue by dnnagy** [divamgupta/diffusionbee-stable-diffusion-ui#379]
Can you add support for [safetensors](https://github.com/huggingface/safetensors) file format for custom models?

**Comment by josepoco** [comment]
yes please!

**Comment by terion-name** [comment]
was very confused that it dosn't support them (

**Comment by TotalDay** [comment]
How to import [safetensors](https://github.com/huggingface/safetensors) file format?

**Comment by wayjam** [comment]
+1

**Comment by RockchinA** [comment]
+1

**Comment by sunyu1984** [comment]
+1

**Comment by nasawz** [comment]
+1

**Comment by Ghostkwebb** [comment]
+1

**Comment by i6941** [comment]
+1,please

**Comment by hsulin** [comment]
+1

**Comment by RBcloud1** [comment]
+1

**Comment by tenamynnek** [comment]
yes please.. no response for 3 months

**Comment by hooligan520** [comment]
+1

**Comment by joelbass** [comment]
Yes, please!

**Comment by sponge1220** [comment]
+1

**Comment by logiota** [comment]
yes please!

**Comment by divamgupta** [comment]
If anyone could send a PR, that would be great. Should not be hard to do. Just add a function to convert_model

**Comment by xiaojue** [comment]
+1

**Comment by ryoyama0508** [comment]
+1

**Comment by martinst** [comment]
Any progress on this. Seems like a really important feature.

**Comment by divamgupta** [comment]
safetensors support added in 5f90f8b8990920593c4a6d4dd54e099a705bafa0

**Comment by lj19950508** [comment]
When will a new version be released along with this feature 。 Are there any steps to build on m1? My own build seems to be missing some files

**Comment by damian-w** [comment]
Following up on this one too... any update on expected release, or how we could build it ourselves?

**Comment by madleech** [comment]
1.7.4 was released yesterday with safetensors support! https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4
