### ISSUE TITLE
Add support for LoRA models?

### ISSUE THREAD

**Issue by zwzheng45** [divamgupta/diffusionbee-stable-diffusion-ui#394]
Is there any plan for supporting LoRA models? These small models makes it easier to fine-tune SD models.

**Comment by freaky-m0** [comment]
Is it simply not possible or why is this open for so long? :D I think 48 upvotes ist a lot ;) 

Thanks for this amazing app btw!!! :D

**Comment by huexley** [comment]
sadly no Lora is a total no-go

**Comment by freaky-m0** [comment]
https://github.com/cmdr2/stable-diffusion-ui/issues/1170

I found something @huexley 

I think this issue should be closed.

**Comment by freaky-m0** [comment]
But this is promising:

https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/4f507cc5027a8a2c62c9ca5571142de7c046b8dc

**Comment by Schneppi** [comment]
Please add https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/4f507cc5027a8a2c62c9ca5571142de7c046b8dc 👍

**Comment by divamgupta** [comment]
Added in latest release. Check the latest release in the releases page on github.

**Comment by fortinmike** [comment]
I see LoRA Tools to generate a new model by adding LoRA weights, but no way to just use LoRA models as "add-ons" to an existing model on-the-fly (using special LoRA tags in the prompt), like it seems to work in for example _stable-diffusion-webui_. How should LoRA models be used in DiffusionBee as of beta 2.2.0?
