### ISSUE TITLE
Feature Request - Generate Variations

### ISSUE THREAD

**Issue by KevinCrossDCL** [divamgupta/diffusionbee-stable-diffusion-ui#397]
Like Dall-E2 can we please have a generate variations button that would create similar images close to the selected image? When you do multiple images at once they are often all very different, and there's sometimes one that's close to what you're after but not perfect, so getting multiple variations on a selected image should help us get closer to what we're after.

**Comment by divamgupta** [comment]
Yes, nice idea

**Comment by divamgupta** [comment]
Added in latest release. Check the latest release in the released page on github.
