### ISSUE TITLE
diffusionbee doesn't any model from civitai.com ?

### ISSUE THREAD

**Issue by tenamynnek** [divamgupta/diffusionbee-stable-diffusion-ui#402]
i just wonder... everyone upload the model from civitai.com
but it can't import to diffusionbee ?

so, where is everyone get the model for diffusionbee here ?

**Comment by KaimingWan** [comment]
same question

**Comment by damozhang** [comment]
same

**Comment by divamgupta** [comment]
You have to download the .ckpt file.

**Comment by dli77** [comment]
> You have to download the .ckpt file.

Will there be a new release to include support for .safetensors? Thanks.

**Comment by rozek** [comment]
support for ".safetensors" has already been added a while ago with [this commit](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/5f90f8b8990920593c4a6d4dd54e099a705bafa0), but a new release has not yet been published...

**Comment by divamgupta** [comment]
try this : https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4

it should work with all models now, if it does not, please post here!

**Comment by threadedblue** [comment]
Working with v1.7.4 and
https://github.com/cloneofsimo/lora.git
example_loras/

I tried to import many different safetensor files I always get the following:

Error Traceback (most recent call last):
File "diffusionbee_backend.py", line 325, in <module>
File "convert_model.py", line 80, in convert_model
ValueError: The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file
[24116] Failed to execute script 'diffusionbee_backend' due to unhandled exception!

**Comment by artist321** [comment]
Approve, 

Error Traceback (most recent call last):
File "diffusionbee_backend.py", line 325, in
File "convert_model.py", line 80, in convert_model

as LoRa in .safetensors

**Comment by keman5** [comment]
I tried to import lora model and got this error:

<img width="284" alt="iShot_2023-05-20_上午10 39 06" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/116868115/4e1c3fe9-f00b-45fe-a1e9-6c07211f44b9">

**Comment by camilovietnam** [comment]
Works fine for me: 
Running DiffusionBee 1.7.1, on MacOS Ventura 13.1, under Python 3.10.8

**Comment by divamgupta** [comment]
Fixed in latest release. Check the latest release in the releases page on github.

**Comment by themagicalmammal** [comment]
No, its still there.

**Comment by themagicalmammal** [comment]
Have it on the nai leaked version.

**Comment by koraysels** [comment]
same issue even with latest beta and th eexample_lora from the lora repo metnioned above.. 


> Working with v1.7.4 and https://github.com/cloneofsimo/lora.git example_loras/
> 
> I tried to import many different safetensor files I always get the following:
> 
> Error Traceback (most recent call last): File "diffusionbee_backend.py", line 325, in File "convert_model.py", line 80, in convert_model ValueError: The model is not supported. Please make sure it is a valid SD 1.4/1.5/2.1 .ckpt/safetensor file [24116] Failed to execute script 'diffusionbee_backend' due to unhandled exception!


ERROR: 


![image](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/2418853/9381dca3-abd8-425e-8c17-f8d53e401fc7)

**Comment by NicestRudeGuy** [comment]
I tried to import some models faced the same error 
![image](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/9863419/01a7d020-6a2c-4fa9-9375-9b042a8abd3f)

**Comment by EmilMoe** [comment]
Same error

**Comment by rodrigocipriani** [comment]
Ssame here

**Comment by guelug** [comment]
does this ever get solved?

**Comment by arifirfan06** [comment]
I still got the error

**Comment by ill-yes** [comment]
Any updates so far?

**Comment by Nomaleus** [comment]
Still can't import models from civitai =(

**Comment by kimslawson** [comment]
Same error here with 2.5.3 and 2.5.1
