### ISSUE TITLE
Please add support for safetensor

### ISSUE THREAD

**Issue by nuoluo** [divamgupta/diffusionbee-stable-diffusion-ui#406]

**Comment by jwjordan** [comment]
I also would love support for safetensors files. In the meantime, is anyone aware of a way to convert safetensors to ckpt files? I haven't found anything that works so far.

**Comment by rozek** [comment]
wasn#T support for ".safetensors" added a while ago with [this commit](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/commit/5f90f8b8990920593c4a6d4dd54e099a705bafa0)?

**Comment by divamgupta** [comment]
https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4

**Comment by rozek** [comment]
Thank you very much for your continuing effort!
