### ISSUE TITLE
Feature Request: Dark Mode / Dark Interface

### ISSUE THREAD

**Issue by jemueller** [divamgupta/diffusionbee-stable-diffusion-ui#41]
first of all i want to say thank you for making this project, its amazing.

but i am going snow blind from staring at the bright white interface tho lol... would be greatly appreciated if there was an option to switch to a black or dark grey interface for dark mode.... would be helpful in the day, necessary at night.

would make this project perfect imo.

thank you again.

**Comment by divamgupta** [comment]
Thanks for the suggestion. Ive added it to my list.

**Comment by jemueller** [comment]
thank you

**Comment by Iktwo** [comment]
Added an initial implementation that follows system settings https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/pull/113
