### ISSUE TITLE
unable to load custom model for inpainting

### ISSUE THREAD

**Issue by rozek** [divamgupta/diffusionbee-stable-diffusion-ui#411]
While loading custom "text-to-image" models ("checkpoint" and "pickletensor" files) works like a charm, loading custom "inpaint" models always aborts with the following error message

```
Error Traceback (most recent call last):
File "convert_model.py", line 85, in <module>
AssertionError: ('shape mismatch at', 'model.diffusion_model.input_blocks.0.0.weight', [320, 9, 3, 3], (320, 4, 3, 3))
[53340] Failed to execute script 'convert_model' due to unhandled exception!
```

Is there any way to load custom models for inpainting as well?

**Comment by divamgupta** [comment]
Added in latest release. Check the latest release in the released page on github.

**Comment by fortinmike** [comment]
The option does seem to be available, but when choosing a custom model, clicking on `Generate` does nothing. It works with the `SD1.5_Inpainting` model but none of the others I imported do anything (inpaint-specific or not). Any insight, @divamgupta ?
