### ISSUE TITLE
Downloaded DiffusionBee for the first time. The generated image is completely black. What is the reason?

### ISSUE THREAD

**Issue by AlexandrCute** [divamgupta/diffusionbee-stable-diffusion-ui#415]
<img width="771" alt="Снимок экрана 2023-04-28 в 14 51 43" src="https://user-images.githubusercontent.com/131523350/235141427-99799537-a549-43ad-a48f-9be08240dacc.png">

**Comment by divamgupta** [comment]
What are your hardware specs and OS version?

**Comment by divamgupta** [comment]
Could you try the new release : https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4

**Comment by AlexandrCute** [comment]
> Какие у вас аппаратные характеристики и версия ОС?

The characteristics are as follows: 
<img width="564" alt="Снимок экрана 2023-04-30 в 22 08 19" src="https://user-images.githubusercontent.com/131523350/235371861-c9bdd197-fef5-4521-a822-bb3ca2d30e86.png">

**Comment by AlexandrCute** [comment]
> Не могли бы вы попробовать новую версию: [https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4 .](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4)

If you install a new version, then you need to delete the old one or what?

**Comment by AlexandrCute** [comment]
> > > Не могли бы вы попробовать новую версию: [https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4 .](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4)
> > 
> > 
> > If you install a new version, then you need to delete the old one or what?
> 
> You can but you don't have to. When installing and moving the app into the applications folder, you should get a prompt to replace the existing app file or keep both.

**Comment by AlexandrCute** [comment]
> > > Не могли бы вы попробовать новую версию: [https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4 .](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.7.4)
> > 
> > 
> > Если ставить новую версию, то старую надо удалять что ли?
> 
> Вы можете, но не обязаны. При установке и перемещении приложения в папку приложений вы должны получить предложение заменить существующий файл приложения или сохранить оба.

Thank you.
