### ISSUE TITLE
[feature request] Numeric Guidance scale

### ISSUE THREAD

**Issue by Mornmacgee** [divamgupta/diffusionbee-stable-diffusion-ui#436]
Thank you for this great app, works fine on my Imac Intel. Really great job!

[feature request]
Slider Guidance scale can be very tricky to adjust when trying to reproduce another prompt adjustement. Could consider the possibility of a numeric alternative to the slider?
Thanks in advance.

**Comment by divamgupta** [comment]
Added in latest release. Check the latest release in the released page on github.
