### ISSUE TITLE
Backend quit unexpectedly on M1 macos 14

### ISSUE THREAD

**Issue by Richert-mark** [divamgupta/diffusionbee-stable-diffusion-ui#439]
I meet a problem when using Diffusionbee, the hardware and software is:
M1 Macbook Air, 8GB, Macos 14 beta 1,
the screenshot is below:
<img width="260" alt="Snipaste_2023-06-20_11-44-48" src="https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/97961600/73ce5e07-5b4f-4e9b-9e43-53906bf26f43">
By searching the solution, it is said that I need to add --no-half to run stable diffusion on M1, but I don't know where I can add it when setup diffusionbee.

**Comment by divamgupta** [comment]
fixed in latest release
