### ISSUE TITLE
Backend quit unexpectedly

### ISSUE THREAD

**Issue by IDEall** [divamgupta/diffusionbee-stable-diffusion-ui#458]
M1 w/ Sonoma 

Backend quit unexpectedly. del:qos:qIndex:modelStringID:options:error:: ANEProgramProcessRequestDirect() Failed with status=0xf : statusType=0x9: Program Inference timeout: timed out}'
multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

**Comment by divamgupta** [comment]
Try the latest version of DiffusionBee
