### ISSUE TITLE
bee 2.4.3 does not working on OSX 12.7.2 systems

### ISSUE THREAD

**Issue by allenzha** [divamgupta/diffusionbee-stable-diffusion-ui#495]
**Support for older OSX systems would be appreciated!**

My computer hardware is mac pro 2013，See screenshot information
![osx 12 7 2](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/1571697/a526e31f-dcf5-4e9d-b110-e16a34d1b468)

**Comment by divamgupta** [comment]
For Intel, you need macos13
