### ISSUE TITLE
Feature Request: add generation string as file comment

### ISSUE THREAD

**Issue by Obsouleet** [divamgupta/diffusionbee-stable-diffusion-ui#50]
Actually I add the generation string manually to the image file if I save it. It would be nice to have this automatically. An other option would be to save a .tct file with all the pictures paramters.

This way one can try to replicate the picture (kind of)

**Comment by iangilman** [comment]
I too would love this!

Another possibility might be to store it in the description field of the PNG metadata. I don't know if that's easier to access, though, so it might not be such a good choice.

BTW, I assume by .tct file, you mean .txt?

**Comment by Obsouleet** [comment]
> BTW, I assume by .tct file, you mean .txt?

Sure - a typo. I meant .txt

**Comment by duanemoody** [comment]
.PNG metadata has the advantage of being cross-platform but honestly I don't see this as an either/or thing, perhaps better as a pair of checkbox preferences. In theory Windows is starting to support extended file attributes, but in practice they're .DS_Store files on non-Apple filesystems.
