### ISSUE TITLE
Hdibdj jdjbdibe 

### ISSUE THREAD

**Issue by Mi13891389** [divamgupta/diffusionbee-stable-diffusion-ui#503]
Jjdib ciowbdojeb didu

**Comment by Mi13891389** [comment]
1. 

- [ ] _
![1706210220314](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/157737077/85a08b52-70d6-4b2b-a0ae-70cfbc9a3e79)
![1706210094160](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/assets/157737077/5e696062-5be3-467f-b6b4-e2c15016b798)
_

**Comment by thisplantguy** [comment]
Umm... what?
