### ISSUE TITLE
Input for Seed Value

### ISSUE THREAD

**Issue by mgo-design** [divamgupta/diffusionbee-stable-diffusion-ui#51]
First of all: thanks for this easy to use tool!
The only thing I am missing ATM is an input value for the seed. I guess I could change the code myself if I tried harder, just not sure where to start. Is there a quick outline how to build the app and how parameters from the UI .vue are passed to the ... rendering engine?

**Comment by gammons** [comment]
If I am reading the code correctly, [the seed value always seems to be `42`.](https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/blob/aa8a4ff29537cbb9e5862e2a213d754111715002/electron_app/src/components/ImgGenerate.vue#L152)

**Comment by 19wolf** [comment]
If that were true, the output would be almost identical for runs with the same prompt/settings

**Comment by divamgupta** [comment]
Seed added in latest release.
