### ISSUE TITLE
Gfpan and RealEsrgan support

### ISSUE THREAD

**Issue by MrsHorrid** [divamgupta/diffusionbee-stable-diffusion-ui#53]
i think this gui would be perfect if theres support with these two modules

**Comment by divamgupta** [comment]
Thanks for the suggestion! Ill def add them

**Comment by greggh** [comment]
@MrsHorrid if you're still looking to solve this. I use Diffusionbee to generate and then Upscayl to do the RealESRGAN and RealSR work.

https://github.com/upscayl/upscayl
