### ISSUE TITLE
Basic documentation

### ISSUE THREAD

**Issue by Itangalo** [divamgupta/diffusionbee-stable-diffusion-ui#57]
We are a few people interested in writing and maintaining documentation for DiffusionBee. This is an issue for discussing the form for that documentation.

### Current idea

**Idea:** Keep documentation in a separate GitHub repository, until DiffusionBee development has slowed down enough to make it reasonable to have the docs in the main project.

**Why:** @divamgupta is (rightly) focusing the energy on moving DiffusionBee forwards. This also means that there is not enough time to review issues concerning documentation. Keeping the docs in a separate repo allows others to maintain the docs, while divamgupta can focus on his awesome magic.

**Some other thoughts**

* The docs repo would ideally be owned by @divamgupta, with docs writers added as co-maintainers (with commit access). But it could also be owned by someone else.
* If the docs is deemed good enough, it would make sense to have a link from the GitHub landing page for DiffusionBee, and probably also at diffusionbee.com.

### Other ideas

* **Put the documentation in a Google Doc** (plus possibly keeping non-trivial issues for the docs in this issue queue). Is this a better option, just to get going?
* Keep the documentation in a wiki on the DiffusionBee project on GitHub. (That would require open up access for more people. Uncertain of what permission.)
* Keep the documentation in markdown files in the DiffusionBee repository. (That would require commit access for more people.)

**Comment by divamgupta** [comment]
That will be helpful! Wiki would be great!

**Comment by Itangalo** [comment]
I think you're the only one who can create a wiki for this project. I'm aiming for documentation in a markdown file in the repo for now, but would be happy to add it to a wiki instead.

Hope to add a pull request with some documentation shortly.

**Comment by Itangalo** [comment]
Pull request available at #139

**Comment by Itangalo** [comment]
Again: Feel free to add the proposed documentation to a wiki instead (but it will probably be more difficult for others to maintain it that way).

**Comment by Itangalo** [comment]
I just updated the description for this issue – I'm now suggesting that the documentation (for the time being) is kept in a separate repository on GitHub.

**Comment by Itangalo** [comment]
Here's another idea, imported from discussion in #139: Putting documentation in a Google Doc. That would be dead simple for people to access, as long as there's a link provided somewhere.

(Having documentation on diffusionbee.com would of course be the best option, but not if it detracts the maintainer from doing awesome stuff with the application.)

**Comment by Itangalo** [comment]
Documentation now merged into the main branch! Closing this issue.
