### ISSUE TITLE
"This application is not supported on this Mac"

### ISSUE THREAD

**Issue by Luen** [divamgupta/diffusionbee-stable-diffusion-ui#70]
You can't open the application "DiffusionBee" because this application is not supported on this Mac.
![Screen Shot 2022-09-20 at 10 38 29 am](https://user-images.githubusercontent.com/1161837/191142735-5d72b022-6af8-4ff2-9884-3dcd21fb1c13.png)
Computer specs:
![Screen Shot 2022-09-20 at 10 39 34 am](https://user-images.githubusercontent.com/1161837/191142860-2d9e3ba4-56b2-4478-ac98-ac0bf64dc9d6.png)

**Comment by ileff** [comment]
this currently works with M1 or M2 chip. your system is an intel cpu.

**Comment by Luen** [comment]
Thank you. Sorry - new to Mac.
