### ISSUE TITLE
Fake backend contains reference to authors local file system

### ISSUE THREAD

**Issue by fleharty** [divamgupta/diffusionbee-stable-diffusion-ui#73]
fake_backend.py

        impath = "/Users/divamgupta/Downloads/output_fork.png?%d"%random.randint(0,10000)

**Comment by fleharty** [comment]
Also has something really curious:
    if random.randint(0,10) > 7:
        print("sdbk errr just a random error lol")
        return

Is the intent here to randomly fail 30% of the time?

**Comment by divamgupta** [comment]
The fake backend is just to test the functionality of the electron app, which includes displaying errors.
