### ISSUE TITLE
0.2.0 Released. 

### ISSUE THREAD

**Issue by divamgupta** [divamgupta/diffusionbee-stable-diffusion-ui#77]
Hello everyone, 

Version 0.2.0 has been released.

Can people comment on how much time it is taking to generate one image for both versions. Also please mention your system specs and OS version. Thanks.

Link to 0.1.0:  https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/download/0.1.0/DiffusionBee-0.1.0-arm64.dmg
Link to 0.2.0: https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/download/0.2.0/DiffusionBee-0.2.0-arm64.dmg

**Comment by xstast24** [comment]
Hi, I would like to test it. Where are the downloaded weights/models located, please? I want to manually backup them on my local drive, so I can easily switch between v0.1/v0.2 without the need for a long download every time. :-) Good job btw!

**Comment by Obsouleet** [comment]
The generation time seems to be nearly the same for me - but I don't get any useful pictures with 0.2.0. Everytime such greyish garbage.
![void](https://user-images.githubusercontent.com/12202450/191529533-7e00147c-48de-44b4-a0bd-d3b0bcf7b411.png)

**Comment by divamgupta** [comment]
@xstast24 the weights are stored in ~/.diffusionbee/downloads .
Version 0.2.0 wont remove the weights for v0.1.0.

**Comment by Obsouleet** [comment]
> @Obsouleet what are your system specs and OS version?

Studio M1 Max / 32 GB RAM / macOS Ventura

**Comment by Obsouleet** [comment]
I'm sure these errors have smth to do with my missing outputs:

<img width="1041" alt="void" src="https://user-images.githubusercontent.com/12202450/191532694-74c31abd-a3ac-4033-b09b-b1ee02c21029.png">

**Comment by interhive** [comment]
I have similar errors to @Obsouleet, but I can generate images. The generation time seems a bit longer, but I am going to test between 1.0 and 2.0 to make sure.

M1 Max / 32 GB RAM / MacOS Monterey 12.6

![Screen Shot 2022-09-21 at 9 56 32 AM](https://user-images.githubusercontent.com/8636/191539054-4ddf2eaf-7114-43e5-99d5-529060a2a5e2.png)

**Comment by jturnerpdx** [comment]
Images do seem to be generating faster. I did notice in the logs the same tensor flow issues above

**Comment by dseddah** [comment]
The tensor flow version is slower than the pytorch version btw. From 19s to 23s for the same prompt ("a dragon in front of a burning building. Marvel Style.")
first one is 0.10, second is 0.20
![image](https://user-images.githubusercontent.com/4643799/191545306-0cdc8cb6-354c-4832-993a-850f656fec8f.png)


![image](https://user-images.githubusercontent.com/4643799/191545146-d5649b86-5da4-47fb-a096-c8a6ce6f47cc.png)

**Comment by divamgupta** [comment]
> The tensor flow version is slower than the pytorch version btw. From 19s to 23s for the same prompt ("a dragon in front of a burning building. Marvel Style.") first one is 0.10, second is 0.20 ![image](https://user-images.githubusercontent.com/4643799/191545306-0cdc8cb6-354c-4832-993a-850f656fec8f.png)
> 
> ![image](https://user-images.githubusercontent.com/4643799/191545146-d5649b86-5da4-47fb-a096-c8a6ce6f47cc.png)

Thanks for the numbers. What are your system specs?

**Comment by divamgupta** [comment]
@dseddah Thanks for the numbers. What are your system specs?

**Comment by sebamacchia** [comment]
it's possible that it does not take long prompts, more than 50 words?

**Comment by dr0idattack** [comment]
I'm having issues as above. Just a blank gray image (and v1 used to work well.) 

MBP 14" running latest public beta of Ventura
 Chip:	Apple M1 Pro
  Total Number of Cores:	10 (8 performance and 2 efficiency)
  Memory:	16 GB

**Comment by kim0** [comment]
Getting only gray block output too. Here's the model files I have, does that look good?
```
$ ls -lh ~/.diffusionbee/downloads
total 17090784
drwxr-xr-x@ 3 kim0  staff    96B Sep 19 20:39 clip_transformer
-rw-r--r--@ 1 kim0  staff   325M Sep 19 20:39 clip_transformer.zip
-rw-r--r--@ 1 kim0  staff   189M Sep 21 16:49 decoder.h5
-rw-r--r--@ 1 kim0  staff   3.2G Sep 21 16:45 diffusion_model.h5
-rw-r--r--@ 1 kim0  staff   4.0G Sep 19 20:36 sd-v1-4.ckpt
-rw-r--r--@ 1 kim0  staff   470M Sep 21 16:48 text_encoder.h5
```

I'm on M1 pro, 16GB RAM (I have chrome running though). Is it possible to run this from the command line too to gather more debug info ?

**Comment by NewCoffee7477** [comment]
Same issue. MacBook 14" M1 Pro 16GB

**Comment by Maki9009** [comment]
when I replace the model with my own custom model it doesn't let me start the application.

**Comment by MattKevan** [comment]
I'm having the same problem with a 16gb M1 Air. Getting grey images and the errors in the log are the same as above.

**Comment by Gitterman69** [comment]
MacBook Pro 2021 14 inch m1 pro 

So it is working for me but the performance is rather slow (4-7s/it)... also the resolutions/options are super limited with the app .... you should really take a look at https://github.com/glonlas/Stable-Diffusion-Apple-Silicon-M1-Install <= this is so far the best m1 compatible stable diffusion version I found. since its mps optimized/enabled I get 1-2s/it with my Mac per batch.... I am not sure though what magic juice gives https://github.com/glonlas/Stable-Diffusion-Apple-Silicon-M1-Install the performance over all other solutions (nightly PyTorch with mps enabled?)....

your gui with the performance from the other GitHub site would be the best of both worlds.....

sorry for the late night rant/bug report :)

############
<img width="840" alt="image" src="https://user-images.githubusercontent.com/113683801/191584829-1c6356e9-a075-463f-b706-717575d61406.png">

**Comment by ChDel** [comment]
very frustrating to have the gray image and no clear instruction how to make this work again, Including the issue with tensorlfow 2.6...
0.1.0 was so much better... :(

**Comment by Gitterman69** [comment]
try the github i posted… works flawless with gpu support

>

**Comment by mehaukulyk** [comment]
Hi , works like a dream for me , Mac Studio Ultra with 128 gb ram and 4 tb hd, I like the new version ;-) good to be able to render 14 images in one shot, look forward to having image to image functionality, when do you think this will be implemented ? also can you explain how to use the paste and match style function , I can't find any readme doc that explains this. also is it possible to save all 14 renders with one save action? Thank you so much for putting this together , and for all your hard work to make it easy for a non tech person like me ;-) brilliant work ! lots of love and kind regards , mehau kulyk

**Comment by ioma8** [comment]
Version 0.20 definitely slower on MacBook Pro M1 32GB RAM than version 0.10

**Comment by daaain** [comment]
Just to offer another data point, I'm getting decent speed out of this new version:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/69962/191740062-99c812c5-7f2b-4979-8782-8d164d52ac17.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/69962/191740106-67547382-6f73-4df3-87f1-3305bd63d0db.png">

**Comment by jjsanderson** [comment]
M1 MacBook Pro, 16Gb RAM, macOS Monterey 12.6. A couple of quick tests:

Diffusion Bee 0.1, run time ~1:30  
Diffusion Bee 0.2, run time ~1:00  

Big thanks for your work on this!

**Comment by murphy2712** [comment]
Hello,
M1 MacBook Pro, 10 cores, 32Gb RAM, Monterey 12.6.
Default settings, except 50 steps.

Diffusion Bee 0.1.0 ~1:10
Diffusion Bee 0.2.1 ~0:52

However I noticed that v0.2 doesn't run with big queries. Like this one:
"ethereal glowing mystery portal to another world, seen by wanderer girl in middle of woods, magic colors, fantasy, trending on artstation, artgerm, cgsociety, greg rutkowski, peter mobrhacher, cinematic, elegant, intricate, ilya kuvshinov, cushart krentz, alphonse mucha, unreal engine, very smooth, high detail, 4 k, concept art, brush strokes, pixiv art, sharp focus, raging dynamic sky, anime art"

Thanks a lot for this local and easy to use app!

**Comment by dseddah** [comment]
> M1 MacBook Pro (13" base M1, 8/8//16 CPU/GPU/Neural cores), 16Gb RAM, macOS Monterey 12.6. A couple of quick tests:
> 
> Diffusion Bee 0.1, run time ~1:30 Diffusion Bee 0.2, run time ~1:00
> 
> Big thanks for your work on this!

that's a bit slow, no ?

**Comment by jjsanderson** [comment]
> that's a bit slow, no ?

Looks about right against @murphy2712's figures from an M1 Pro, I'd have thought. But other than that I've no idea. :-)

**Comment by dseddah** [comment]
i'm having between 14s and 20s on a macbook pro (M1 max, 64gb of ram). Maybe the ram is the limitation ?

**Comment by dseddah** [comment]
Yeah, you're right. I have 32 gpu cores. I had no idea these beasts were so powerful. I wonder when the neural engine will be usable by pytorch or tensorflow..

**Comment by murphy2712** [comment]
> i'm having between 14s and 20s on a macbook pro (M1 max, 64gb of ram). Maybe the ram is the limitation ?

How many **steps** did you use in the settings? 25 is the default, but for my benchs I use 50 (best results).

**Comment by dseddah** [comment]
I didn't change any settings so it might be 25.

**Comment by zachschrock** [comment]
I'm at 40 seconds per, M1 Ultra 20 CPU cores and 48 GPU cores, 64GB ram. This is when running 768px @ 25 Steps and 4 Guidance Scale.

**Comment by mxcl** [comment]
Since 1.5 has been released, maybe unpin this ticket?
