### ISSUE TITLE
Feature Request [Dark Mode]

### ISSUE THREAD

**Issue by prestmango** [divamgupta/diffusionbee-stable-diffusion-ui#86]
First off, you are doing the work of God ! Phenomenal system to run stable diffusion on Mac.
If possible, a dark mode app would be amazing, to seamlessly use this, and match the modern dark U.I of a Mac. If there was a setting in preferences to switch the U.I to be dark grey, or black, that would be amazing :)))

**Comment by LePips** [comment]
Duplicate of https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/issues/41
