### ISSUE TITLE
Generated images are always empty on macOS Ventura

### ISSUE THREAD

**Issue by VXenomac** [divamgupta/diffusionbee-stable-diffusion-ui#93]
My system version is macOS Ventura 13.0 Beta(22A5352e), and generated images are always empty on macOS Ventura
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/21958044/191899926-c19437f2-c52e-4b75-991d-94f27e37b60b.png">

**Comment by VXenomac** [comment]
System specs:
MacBook Pro 16 inch 2021
Apple M1 Max
64GB RAM
macOS Ventura 13.0 Beta(22A5352e)

**Comment by divamgupta** [comment]
Fixed in the latest release

**Comment by VXenomac** [comment]
Yes, thanks!
This issue does not reproduce in the latest version 0.2.1 (0003).
